/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rozpoznawanie_zad1_klasyf;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;


/**
 *
 * @author Michał
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    String trainingSetFilepath = null;
    String unknownSetFilepath = null;
    Loader k = null;
    KNN knn = null;
    
    
    long start_time;
    long end_time;
    long difference;
    long minutes;
    long seconds;
    
    int K;
    int metricType;
    
    boolean isCalculating = false;
    
    
    public MainWindow() {
        initComponents();
        
        jProgressPanel.setVisible(false);
        jButtonTrainingChart.setVisible(false);
        jButtonUnknownChart.setVisible(false);
        jTotalTimeText.setVisible(false);
        jTotalTimeLabel.setVisible(false);
        jResultsPanel.setVisible(false);
        /*jButtonRunKNN.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent arg0){
                
                new Thread(new Runnable(){

                    @Override
                    public void run() {
                        ShowProgressPanel(true);
                        jProgressBar.setIndeterminate(true);
                        System.out.println("IN");
                    }
                }).start();
            }
        });*/
        //jFileChooser.set
        //jProgressBar.addChangeListener(new ChangeListener(){
           /* public void stateChanged(ChangeEvent evt){
                JProgressBar comp = (JProgressBar) evt.getSource();
                int value = comp.getValue();
                int min = comp.getMinimum();
                int max = comp.getMaximum();
            }
        });*/
    }
    
    public int GetData()
    {
        k = new Loader();
        return 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jProgressPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jEstimatedTimeText = new javax.swing.JLabel();
        jTotalTimeLabel = new javax.swing.JLabel();
        jTotalTimeText = new javax.swing.JLabel();
        jFilepathPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton_TrainingSearch = new javax.swing.JButton();
        jButton_UnknownSearch = new javax.swing.JButton();
        jTF_TrainingFilepath = new javax.swing.JTextField();
        jTF_UnknownFilepath = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonTrainingChart = new javax.swing.JButton();
        jButtonUnknownChart = new javax.swing.JButton();
        jMetricPanel = new javax.swing.JPanel();
        jMetricComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jButtonRunKNN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jText_KNeighbours = new javax.swing.JTextField();
        jResultsPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jResult = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        j4Result = new javax.swing.JLabel();
        j3Result = new javax.swing.JLabel();
        j5Result = new javax.swing.JLabel();
        j6Result = new javax.swing.JLabel();
        j7Result = new javax.swing.JLabel();
        j8Result = new javax.swing.JLabel();
        j9Result = new javax.swing.JLabel();
        j2Result = new javax.swing.JLabel();
        j1Result = new javax.swing.JLabel();
        j0Result = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jOpenResultsButton = new javax.swing.JButton();

        jFileChooser.setCurrentDirectory(new java.io.File("C:\\Users\\Michał\\Documents\\NetBeansProjects\\Rozpoznawanie_zad1_klasyf\\features"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(832, 530));

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel1.setText("Klasyfikator KNN");

        jLabel2.setText("Overal progress");

        jProgressBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fff(evt);
            }
        });
        jProgressBar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jProgressBarPropertyChange(evt);
            }
        });

        jLabel3.setText("Estimated time:");

        jEstimatedTimeText.setText("0m 0s");

        jTotalTimeLabel.setText("Total time:");

        jTotalTimeText.setText("0m 0s");

        javax.swing.GroupLayout jProgressPanelLayout = new javax.swing.GroupLayout(jProgressPanel);
        jProgressPanel.setLayout(jProgressPanelLayout);
        jProgressPanelLayout.setHorizontalGroup(
            jProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jProgressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jProgressPanelLayout.createSequentialGroup()
                            .addComponent(jTotalTimeLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTotalTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jProgressPanelLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(jEstimatedTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jProgressPanelLayout.setVerticalGroup(
            jProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jProgressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jEstimatedTimeText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTotalTimeLabel)
                    .addComponent(jTotalTimeText))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jButton1.setText("Load");
        jButton1.setEnabled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Load");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton_TrainingSearch.setText("...");
        jButton_TrainingSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TrainingSearchActionPerformed(evt);
            }
        });

        jButton_UnknownSearch.setText("...");
        jButton_UnknownSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UnknownSearchActionPerformed(evt);
            }
        });

        jTF_TrainingFilepath.setForeground(new java.awt.Color(64, 64, 64));
        jTF_TrainingFilepath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_TrainingFilepathActionPerformed(evt);
            }
        });

        jTF_UnknownFilepath.setForeground(new java.awt.Color(64, 64, 64));
        jTF_UnknownFilepath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_UnknownFilepathActionPerformed(evt);
            }
        });

        jLabel5.setText("Training set filepath:");

        jLabel6.setText("Unknown set filepath:");

        jButtonTrainingChart.setForeground(new java.awt.Color(32, 164, 32));
        jButtonTrainingChart.setText("Chart");
        jButtonTrainingChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrainingChartActionPerformed(evt);
            }
        });

        jButtonUnknownChart.setForeground(new java.awt.Color(32, 164, 32));
        jButtonUnknownChart.setText("Chart");
        jButtonUnknownChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnknownChartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFilepathPanelLayout = new javax.swing.GroupLayout(jFilepathPanel);
        jFilepathPanel.setLayout(jFilepathPanelLayout);
        jFilepathPanelLayout.setHorizontalGroup(
            jFilepathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFilepathPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFilepathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFilepathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTF_UnknownFilepath, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_TrainingFilepath, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jFilepathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_TrainingSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_UnknownSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jFilepathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFilepathPanelLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUnknownChart))
                    .addGroup(jFilepathPanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTrainingChart)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jFilepathPanelLayout.setVerticalGroup(
            jFilepathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFilepathPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFilepathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFilepathPanelLayout.createSequentialGroup()
                        .addGroup(jFilepathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonTrainingChart))
                        .addGap(18, 18, 18)
                        .addGroup(jFilepathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButtonUnknownChart)))
                    .addGroup(jFilepathPanelLayout.createSequentialGroup()
                        .addGroup(jFilepathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTF_TrainingFilepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_TrainingSearch)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jFilepathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_UnknownSearch)
                            .addGroup(jFilepathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jTF_UnknownFilepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        jMetricComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Euklides", "Manhattan", "Czebyszew", "Minkowski" }));

        jLabel4.setText("Choose metric:");

        jButtonRunKNN.setText("Run KNN");
        jButtonRunKNN.setEnabled(false);
        jButtonRunKNN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunKNNActionPerformed(evt);
            }
        });

        jLabel7.setText("K-neighbours:");

        jText_KNeighbours.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_KNeighbours.setText("5");
        jText_KNeighbours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_KNeighboursActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jMetricPanelLayout = new javax.swing.GroupLayout(jMetricPanel);
        jMetricPanel.setLayout(jMetricPanelLayout);
        jMetricPanelLayout.setHorizontalGroup(
            jMetricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMetricPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jMetricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jMetricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jMetricPanelLayout.createSequentialGroup()
                        .addComponent(jMetricComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonRunKNN, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jText_KNeighbours, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jMetricPanelLayout.setVerticalGroup(
            jMetricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMetricPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jMetricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jMetricComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRunKNN))
                .addGap(18, 18, 18)
                .addGroup(jMetricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jText_KNeighbours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel8.setText("Results");

        jLabel9.setText("Recognized:");

        jResult.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jResult.setText("80%");

        jLabel11.setText("0");

        jLabel12.setText("1");

        jLabel13.setText("2");

        jLabel14.setText("4");

        jLabel15.setText("3");

        jLabel16.setText("5");

        jLabel17.setText("6");

        jLabel18.setText("7");

        jLabel19.setText("8");

        jLabel20.setText("9");

        j4Result.setText("50%");

        j3Result.setText("50%");

        j5Result.setText("50%");

        j6Result.setText("50%");

        j7Result.setText("50%");

        j8Result.setText("50%");

        j9Result.setText("50%");

        j2Result.setText("50%");

        j1Result.setText("50%");

        j0Result.setText("50%");

        jOpenResultsButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jOpenResultsButton.setText("+");
        jOpenResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpenResultsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jResultsPanelLayout = new javax.swing.GroupLayout(jResultsPanel);
        jResultsPanel.setLayout(jResultsPanelLayout);
        jResultsPanelLayout.setHorizontalGroup(
            jResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResultsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jResultsPanelLayout.createSequentialGroup()
                        .addGroup(jResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jResultsPanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)))
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jOpenResultsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j0Result, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j1Result, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j2Result, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j4Result, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j3Result, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j5Result, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j6Result, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j7Result, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j8Result, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j9Result, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jResult, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jResultsPanelLayout.setVerticalGroup(
            jResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResultsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jOpenResultsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jResultsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20))
                    .addGroup(jResultsPanelLayout.createSequentialGroup()
                        .addComponent(j0Result)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j1Result)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j2Result)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j3Result)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j4Result)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j5Result)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j6Result)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j7Result)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j8Result)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j9Result)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jFilepathPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMetricPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jResultsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jFilepathPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jMetricPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 81, Short.MAX_VALUE))
                    .addComponent(jResultsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fff(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fff
        //SetProgressValue(new PropertyChangeEvent, 5);
    }//GEN-LAST:event_fff

    private void jProgressBarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jProgressBarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jProgressBarPropertyChange

    private void jTF_UnknownFilepathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_UnknownFilepathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_UnknownFilepathActionPerformed

    private void jTF_TrainingFilepathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_TrainingFilepathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_TrainingFilepathActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton_UnknownSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UnknownSearchActionPerformed
        int returnVal = jFileChooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            jTF_UnknownFilepath.setText(jFileChooser.getSelectedFile().getAbsolutePath());
            jButton2.setEnabled(true);
        }       
    }//GEN-LAST:event_jButton_UnknownSearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        unknownSetFilepath = jTF_UnknownFilepath.getText();
        k.LoadUnknownGroup(unknownSetFilepath);
        jButtonUnknownChart.setVisible(true);
        if(trainingSetFilepath != null && unknownSetFilepath != null){
                jButtonRunKNN.setEnabled(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonRunKNNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunKNNActionPerformed
        
        if(isCalculating){
            isCalculating = false;
            knn.running = false;
            jButtonRunKNN.setText("Run KNN");
        }else{
            isCalculating = true;
            jButtonRunKNN.setText("Stop KNN");
            jTotalTimeText.setVisible(false);
            jTotalTimeLabel.setVisible(false);
            jEstimatedTimeText.setForeground(Color.black);
            ShowProgressPanel(true);
            try{
                K = Integer.parseInt(jText_KNeighbours.getText());
                if(K>k.unknownNumbersAmount) throw new NumberFormatException();
            }
            catch(NumberFormatException e){
                if(K > k.unknownNumbersAmount){
                    jText_KNeighbours.setText(Integer.toString(k.unknownNumbersAmount));
                    K = k.unknownNumbersAmount;
                }
                else {
                    jText_KNeighbours.setText("5");
                    K = 5;
                }
            }
            metricType = jMetricComboBox.getSelectedIndex();
            System.out.println("Metric: " + metricType );
            knn = new KNN();


            final Timer t = new Timer(250, new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    float progress = knn.GetProgress();
                    long tmpTime = System.currentTimeMillis() - start_time;
                    tmpTime = (long) (tmpTime * 100.0/progress-tmpTime);
                    minutes = TimeUnit.MILLISECONDS.toMinutes(tmpTime);
                    tmpTime -= TimeUnit.MINUTES.toMillis(minutes);
                    seconds = TimeUnit.MILLISECONDS.toSeconds(tmpTime);
                    String estimatedTime = (minutes + "m " + seconds + "s");
                    if(minutes<1000) SetProgress((int)progress, estimatedTime);
                    else SetProgress((int)progress, "?");
                    if(jProgressBar.getValue() == 100){
                        end_time = System.currentTimeMillis() - start_time;
                        minutes = TimeUnit.MILLISECONDS.toMinutes(end_time);
                        end_time -= TimeUnit.MINUTES.toMillis(minutes);
                        seconds = TimeUnit.MILLISECONDS.toSeconds(end_time);
                        String totalTime = (minutes + "m " + seconds + "s");
                        SetProgress(100, "Finished");
                        jEstimatedTimeText.setForeground(new Color(32,164,32));
                        jButtonRunKNN.setText("Run KNN");
                        jTotalTimeText.setText(totalTime);
                        jTotalTimeText.setVisible(true);
                        jTotalTimeLabel.setVisible(true);
                        isCalculating = false;
                        ShowResults(knn.result, knn.resultPerNumber);
                        ((Timer) e.getSource()).stop();
                    }else if(isCalculating == false){
                        end_time = System.currentTimeMillis() - start_time;
                        minutes = TimeUnit.MILLISECONDS.toMinutes(end_time);
                        end_time -= TimeUnit.MINUTES.toMillis(minutes);
                        seconds = TimeUnit.MILLISECONDS.toSeconds(end_time);
                        String totalTime = (minutes + "m " + seconds + "s");
                        jEstimatedTimeText.setText("Aborted");
                        jEstimatedTimeText.setForeground(Color.red);
                        jButtonRunKNN.setText("Run KNN");
                        jTotalTimeText.setText(totalTime);
                        jTotalTimeText.setVisible(true);
                        jTotalTimeLabel.setVisible(true);
                        ((Timer) e.getSource()).stop();
                    }
                }
            });

            Thread t1 = new Thread(new Runnable() {

                @Override
                public void run() {
                   while(isCalculating && knn.progress<100){
                        knn.RunKNN(k.unknownFeatures, k.trainingFeatures, K, metricType, k.classesAmount);
                   }
                }
            });

            start_time = System.currentTimeMillis();
            t.start();
            t1.start();
        }
        
        
    }//GEN-LAST:event_jButtonRunKNNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        trainingSetFilepath = jTF_TrainingFilepath.getText();
        k.LoadTrainingGroup(trainingSetFilepath);
        trainingSetFilepath = jTF_TrainingFilepath.getText();
        jButtonTrainingChart.setVisible(true);
        if(trainingSetFilepath != null && unknownSetFilepath != null){
                jButtonRunKNN.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_TrainingSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TrainingSearchActionPerformed
        int returnVal = jFileChooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            jTF_TrainingFilepath.setText(jFileChooser.getSelectedFile().getAbsolutePath());
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_jButton_TrainingSearchActionPerformed

    private void jButtonTrainingChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrainingChartActionPerformed
        k.TrainingSetChart();
    }//GEN-LAST:event_jButtonTrainingChartActionPerformed

    private void jButtonUnknownChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnknownChartActionPerformed
        k.UnknownSetChart();
    }//GEN-LAST:event_jButtonUnknownChartActionPerformed

    private void jText_KNeighboursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_KNeighboursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_KNeighboursActionPerformed

    private void jOpenResultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpenResultsButtonActionPerformed
        Results results = new Results(knn.result, knn.resultPerNumber, knn.mistakeTab, 0);
        results.setVisible(true);
        MistakeMatrix mistakeMatrix = new MistakeMatrix(knn.result, knn.resultPerNumber, knn.mistakeTab, 0);
        mistakeMatrix.setVisible(true);
    }//GEN-LAST:event_jOpenResultsButtonActionPerformed

    
    void ColorizeResult(JLabel label, float value)
    {
        if(value>90) {
            label.setForeground(new Color(32,164,32));
        }else if(value<70){
             label.setForeground(Color.red);
        }else{
            label.setForeground(Color.black);
        }
    }
   
    
    public void ShowResults(float result, int[][]resultPerNumber)
    {
        float tmp;
        jResult.setText(String.format("%.2f",result*100.0)+"%");
        ColorizeResult(jResult, (float) (result*100.0));
        if(resultPerNumber[0][3]>0){
            tmp = ((float) ((resultPerNumber[0][0]*100.0)/resultPerNumber[0][3]));
            ColorizeResult(j0Result,tmp);
            j0Result.setText(String.format("%.2f",tmp)+"%");
        }else{
            j0Result.setText("-");
        }if(resultPerNumber[1][3]>0){
            tmp = ((float) ((resultPerNumber[1][0]*100.0)/resultPerNumber[1][3]));
            ColorizeResult(j1Result,tmp);
            j1Result.setText(String.format("%.2f",tmp)+"%");
        }else{
            j1Result.setText("-");
        }if(resultPerNumber[2][3]>0){
            tmp = ((float) ((resultPerNumber[2][0]*100.0)/resultPerNumber[2][3]));
            ColorizeResult(j2Result,tmp);
            j2Result.setText(String.format("%.2f",tmp)+"%");
        }else{
            j2Result.setText("-");
        }if(resultPerNumber[3][3]>0){
            tmp = ((float) ((resultPerNumber[3][0]*100.0)/resultPerNumber[3][3]));
            ColorizeResult(j3Result,tmp);
            j3Result.setText(String.format("%.2f",tmp)+"%");
        }else{
            j3Result.setText("-");
        }if(resultPerNumber[4][3]>0){
            tmp = ((float) ((resultPerNumber[4][0]*100.0)/resultPerNumber[4][3]));
            ColorizeResult(j4Result,tmp);
            j4Result.setText(String.format("%.2f",tmp)+"%");
        }else{
            j4Result.setText("-");
        }if(resultPerNumber[5][3]>0){
            tmp = ((float) ((resultPerNumber[5][0]*100.0)/resultPerNumber[5][3]));
            ColorizeResult(j5Result,tmp);
            j5Result.setText(String.format("%.2f",tmp)+"%");
        }else{
            j5Result.setText("-");
        }if(resultPerNumber[6][3]>0){
            tmp = ((float) ((resultPerNumber[6][0]*100.0)/resultPerNumber[6][3]));
            ColorizeResult(j6Result,tmp);
            j6Result.setText(String.format("%.2f",tmp)+"%");
        }else{
            j6Result.setText("-");
        }if(resultPerNumber[7][3]>0){
            tmp = ((float) ((resultPerNumber[7][0]*100.0)/resultPerNumber[7][3]));
            ColorizeResult(j7Result,tmp);
            j7Result.setText(String.format("%.2f",tmp)+"%");
        }else{
            j7Result.setText("-");
        }if(resultPerNumber[8][3]>0){
            tmp = ((float) ((resultPerNumber[8][0]*100.0)/resultPerNumber[8][3]));
            ColorizeResult(j8Result,tmp);
            j8Result.setText(String.format("%.2f",tmp)+"%");
        }else{
            j8Result.setText("-");
        }if(resultPerNumber[9][3]>0){
            tmp = ((float) ((resultPerNumber[9][0]*100.0)/resultPerNumber[9][3]));
            ColorizeResult(j9Result,tmp);
            j9Result.setText(String.format("%.2f",tmp)+"%");
        }else{
            j9Result.setText("-");
        }
        
        /*tmp = ((float) ((resultPerNumber[1][0]*100.0)/resultPerNumber[1][3]));
        j1Result.setText(String.format("%.2f",tmp)+"%");
        ColorizeResult(j1Result,tmp);
        tmp = ((float) ((resultPerNumber[2][0]*100.0)/resultPerNumber[2][3]));
        j2Result.setText(String.format("%.2f",tmp)+"%");
        ColorizeResult(j2Result,tmp);
        tmp = ((float) ((resultPerNumber[3][0]*100.0)/resultPerNumber[3][3]));
        j3Result.setText(String.format("%.2f",tmp)+"%");
        ColorizeResult(j3Result,tmp);
        tmp = ((float) ((resultPerNumber[4][0]*100.0)/resultPerNumber[4][3]));
        j4Result.setText(String.format("%.2f",tmp)+"%");
        ColorizeResult(j4Result,tmp);
        tmp = ((float) ((resultPerNumber[5][0]*100.0)/resultPerNumber[5][3]));
        j5Result.setText(String.format("%.2f",tmp)+"%");
        ColorizeResult(j5Result,tmp);
        tmp = ((float) ((resultPerNumber[6][0]*100.0)/resultPerNumber[6][3]));
        j6Result.setText(String.format("%.2f",tmp)+"%");
        ColorizeResult(j6Result,tmp);
        tmp = ((float) ((resultPerNumber[7][0]*100.0)/resultPerNumber[7][3]));
        j7Result.setText(String.format("%.2f",tmp)+"%");
        ColorizeResult(j7Result,tmp);
        tmp = ((float) ((resultPerNumber[8][0]*100.0)/resultPerNumber[8][3]));
        j8Result.setText(String.format("%.2f",tmp)+"%");
        ColorizeResult(j8Result,tmp);
        tmp = ((float) ((resultPerNumber[9][0]*100.0)/resultPerNumber[9][3]));
        j9Result.setText(String.format("%.2f",tmp)+"%");
        ColorizeResult(j9Result,tmp);*/
        jResultsPanel.setVisible(true);
    }
    
    public void updateBar(int n){
        jProgressBar.setValue(n);
    }
    
    public void SetProgress(int n, String text)
    {
        jProgressBar.setValue(n);
        jProgressBar.setStringPainted(true);
        jEstimatedTimeText.setText(text);
    }

         
    public void ShowMetricPanel(boolean b){
        if(b) jMetricPanel.setVisible(true);
        else jMetricPanel.setVisible(false);
    }
    
    public void ShowProgressPanel(boolean b){
        if(b) jProgressPanel.setVisible(true);
        else jProgressPanel.setVisible(false);
    }
            

//    public void train() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainWindow().setVisible(true);
//            }
//        });
//    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel j0Result;
    private javax.swing.JLabel j1Result;
    private javax.swing.JLabel j2Result;
    private javax.swing.JLabel j3Result;
    private javax.swing.JLabel j4Result;
    private javax.swing.JLabel j5Result;
    private javax.swing.JLabel j6Result;
    private javax.swing.JLabel j7Result;
    private javax.swing.JLabel j8Result;
    private javax.swing.JLabel j9Result;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonRunKNN;
    private javax.swing.JButton jButtonTrainingChart;
    private javax.swing.JButton jButtonUnknownChart;
    private javax.swing.JButton jButton_TrainingSearch;
    private javax.swing.JButton jButton_UnknownSearch;
    private javax.swing.JLabel jEstimatedTimeText;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JPanel jFilepathPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox jMetricComboBox;
    private javax.swing.JPanel jMetricPanel;
    private javax.swing.JButton jOpenResultsButton;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JPanel jProgressPanel;
    private javax.swing.JLabel jResult;
    private javax.swing.JPanel jResultsPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTF_TrainingFilepath;
    private javax.swing.JTextField jTF_UnknownFilepath;
    private javax.swing.JTextField jText_KNeighbours;
    private javax.swing.JLabel jTotalTimeLabel;
    private javax.swing.JLabel jTotalTimeText;
    // End of variables declaration//GEN-END:variables
}
